### ISSUE TITLE
book (p.089) Mont Blanc should be listed at 4,810m 

### ISSUE THREAD

**Issue by louiswh** [cosmos-book/cosmos-book.github.io#10]
From the paperback (p.089) Mont Blanc should be listed at 4,810m (elevation ASL) and not 4,697m (prominence / relative height) given the context. As someone who's climbed whole thing bar the last 100m: it is a not an insignificant difference!

**Comment by slowe** [comment]
@louiswh Thanks for the correction. If the publishers ever release another edition, we'll aim to get this updated.
