### ISSUE TITLE
"Access Denied" error on constellations page

### ISSUE THREAD

**Issue by AntiSol** [cosmos-book/cosmos-book.github.io#11]
I just discovered this repo, it's awesome!

I see an error on the "all 88 constellations" page when I click on any of the constellations:
![Screenshot_2019-08-07_17-58-52](https://user-images.githubusercontent.com/351169/62605382-557e6080-b93d-11e9-985c-de3e4f139c85.jpg)

I see a similar error message when I click on any of the constellations.

**Comment by slowe** [comment]
@AntiSol Thanks for spotting this. It was referring to a URL that no longer works. I've updated it to use a current link for Virtual Sky.

**Comment by AntiSol** [comment]
@slowe Confirmed fixed, thanks! :)
