### ISSUE TITLE
Most of the links do nothing

### ISSUE THREAD

**Issue by manueldeljesus** [cosmos-book/cosmos-book.github.io#2]
I wanted to check some of the content before buying the book but have realized that most of the links have no content, just a title and background color. Most of the graphics that show up do not seem to be interactive. Is this the normal behavior? I'm pretty sure I am missing something but cannot figure out what it is.

Your help is much appreciated

**Comment by chrisnorth** [comment]
Which links are you looking at which have no content? It may be a problem with javascript or your browser. Could you let us know which pages you're looking at and what browser you're using? You can use e.g. whatsmybrowser.org if you're unsure.

Not every infographic has online content, but they should all be interactive, either allowing you to change the view, or providing more information (by clicking).

**Comment by slowe** [comment]
@manueldeljesus No, it is not normal behaviour.

They should be interactive but the interactivity requires Javascript. When you say there is just a title and a background colour, do you also mean that the footer text (scroll down) is missing? As @chrisnorth said, it would be helpful if you provided the URL of a particular page, the name/version of the web browser you are using, and a screenshot of what it looks like for you.

**Comment by manueldeljesus** [comment]
Dear @chrisnorth and @slowe,

Excuse for all the missing information in my initial message. I attach some prints of the screen just to show two of the pages that show no content. I reduced the size in order to save space, but I hope the problem is clear from them. 

<img width="400" alt="captura de pantalla 2015-11-04 a las 17 51 47" src="https://cloud.githubusercontent.com/assets/2642961/10945296/2e181c34-831d-11e5-9a9c-af649461a8f8.png">
<img width="400" alt="captura de pantalla 2015-11-04 a las 17 51 54" src="https://cloud.githubusercontent.com/assets/2642961/10945295/2e14ea50-831d-11e5-9db0-abdbf043739f.png">
<img width="400" alt="captura de pantalla 2015-11-04 a las 17 59 07" src="https://cloud.githubusercontent.com/assets/2642961/10945509/0a3d288a-831e-11e5-9ae0-8bd5333095f0.png">
<img width="400" alt="captura de pantalla 2015-11-04 a las 17 59 11" src="https://cloud.githubusercontent.com/assets/2642961/10945510/0a43c4b0-831e-11e5-8a45-8f5142410e94.png">

This captures has been done with Chrome ( http://whatsmybrowser.org/b/WPXEFJX ) but I got the same behavior on Firefox 41 and Safari 9. I also tried some other links that do not work but the results are similar.

Your help and attention is really appreciated

**Comment by slowe** [comment]
@manueldeljesus It should look like this 
![screen shot 2015-11-04 at 17 17 20](https://cloud.githubusercontent.com/assets/299787/10946083/430f24a2-8318-11e5-9448-b35a3a6d3536.png) and that works for me in Firefox 41, Chrome 46 and Safari 5.1.10.

I notice from your screenshot that you are looking at a locally hosted version. Do you still have the same problem on the web-hosted version? e.g. http://cosmos-book.github.io/human-spaceflight/timeline The problem with a locally-hosted version is that the web-browser's security model forbids the loading of the data file. You can get around that by starting Chrome from the command line with a flag e.g.

`open /Applications/Google\ Chrome.app --args --allow-file-access-from-files`

Firefox has something similar but I can't remember what it is (possibly in about:config) off the top of my head.

Alternatively, you can just visit the web-hosted versions http://cosmos-book.github.io/human-spaceflight/timeline

**Comment by manueldeljesus** [comment]
@slowe The online version just works, which is great. Thank you very much for the help

With respect to the locally hosted version I cannot make it work even when launching Chrome the way you suggested. Having access to the online version is enough for me, so no problem, but I wanted to make the comment just in case

Your help is really appreciated

**Comment by slowe** [comment]
This isn't something that we can fix as it is due to the browser security model when running locally. So I'm marking this as closed.
