### ISSUE TITLE
Juno arrival date (online infographic)

### ISSUE THREAD

**Issue by shargrov** [cosmos-book/cosmos-book.github.io#4]
In the online "Interplanetary Missions" graphic, the date for Juno's arrival at Jupiter is 2016-06-04. It actually enters Jovian orbit 2016-07-04. If the former is meant to signify the beginning of data collection rather than orbital insertion, please disregard.

**Comment by slowe** [comment]
@shargrov Thanks for spotting the typo. It was supposed to be July. I've fixed it.
