### ISSUE TITLE
Exoplanets not showing correctly in Chrome

### ISSUE THREAD

**Issue by chrisnorth** [cosmos-book/cosmos-book.github.io#5]
I spotted that in Chrome ( 50.0.2661.94 on Mac OS X 10.10.5) the exoplanets were all showing up blue (I assume color.blue[0] as that's set at the start:
![image](https://cloud.githubusercontent.com/assets/4124704/15174774/20d72588-175b-11e6-8c3e-eb7ee3d4ca50.png)

Problem seemed to be in svg.selectAll("circle") with error complaining about negative value of attr "r" being <0 (in the case where a planet has d.radius=0). I have a catch to pick up r=0 and return 0 (not <0).

For some reason, the Chrome console error has stopped appearing (are you currently tinkering @slowe ?), but the planets still show up as blue. Can't seem to check local version in Chrome due to sadboxing restrictions.

**Comment by slowe** [comment]
@chrisnorth Two people had mentioned all-blue images but I hadn't been able to find the common issue. Unfortunately I can't check Chrome any more as it no longer "supports" my OS. I'm not tinkering with it at the moment. The only thing I changed recently was to update the CSV file with the list of planets.

**Comment by chrisnorth** [comment]
Was there a radius=0 in there?

+----------------------------------------------------------+
| Dr Chris North
| Research Associate, Undergraduate Admissions Tutor &
| Community Engagement Coordinator
| School of Physics and Astronomy, Cardiff University
| chris.north@astro.cf.ac.uk
| +44 (0)29 208 70537
+----------------------------------------------------------+

**Comment by slowe** [comment]
It seems the radius isn't the issue at all. The problem is that Chrome isn't finding the `background-color` for the appropriate discovery method. i.e. $("&lt;div class='transit'&gt;&lt;/div&gt;").css('backgroundColor') isn't returning what it should be.
