### ISSUE TITLE
Sally Ride

### ISSUE THREAD

**Issue by ToSeek** [cosmos-book/cosmos-book.github.io#6]
On the "Human spaceflight" infographic (12-13), Sally Ride is left off - she flew in 1983.

Also, if Wikipedia is correct (https://en.wikipedia.org/wiki/List_of_female_astronauts), five women flew in space in 1984, not four (Savitskaya, Ride, Resnik, Sullivan, Fisher). They also have four for 1985 rather than three.

**Comment by slowe** [comment]
@ToSeek Thanks for the feedback. Are you referring to the print edition or the website? She is included for STS-7 and STS-41-G on both the main graph page http://cosmos-book.github.io/human-spaceflight/ and the timeline http://cosmos-book.github.io/human-spaceflight/timeline

**Comment by ToSeek** [comment]
I was referring to the print edition and the infographic with the men expressed as dots on the right-hand page and the women on the left. There's no female dot for 1983.

**Comment by slowe** [comment]
@ToSeek I tried to get this fixed in the paperback edition that came out in February 2017 but it seems my corrections didn't get applied. Sorry.

I have since made an online version of the male/female graphic and she is on that http://cosmos-book.github.io/human-spaceflight/yearly

**Comment by ToSeek** [comment]
Thanks for trying!
