### ISSUE TITLE
Who's In Space?

### ISSUE THREAD

**Issue by PherosNike** [cosmos-book/cosmos-book.github.io#7]
Since 19 december 2017 on ISS there are also Norishige Kanai, Scott Tingle and Mark Vande Hei.

**Comment by slowe** [comment]
@PherosNike Thanks for the update. It looks as though Mark Vande Hei had already gone up on Soyuz MS-06 and it was Anton Shkaplerov who went up in December. I've updated the data and graphics with that last launch and some EVAs that were done in October (I was away and missed them).
