### ISSUE TITLE
Comet Discoverers Chart

### ISSUE THREAD

**Issue by rodcomet** [cosmos-book/cosmos-book.github.io#9]
On the chart of comet discoverers, there is an error with A F A L Jones. Albert Jones ( a good friend of mine)discovered only two comets. The third Jones comet was 'Mitchell-Jones-Gerber', which was discovered by Mervyn Jones in Australia.

**Comment by slowe** [comment]
@rodcomet Thanks for spotting this. I've added it to the [Errata page](http://cosmos-book.github.io/errata/index.html).
